#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.MSP430{1,0,4.1,1
#
msp430g2xx3_usci_i2c_slave_rx.x430: package/cfg/msp430g2xx3_usci_i2c_slave_rx.x430.mak

clean::
	-$(RM) package/cfg/msp430g2xx3_usci_i2c_slave_rx.x430.mak
